// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Repositories;

#nullable disable

namespace TodoApp.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20250920153051_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoApp.Models.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("IsDone");

                    b.HasIndex("Priority");

                    b.ToTable("Todos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2799c83-6fb5-46d6-90b2-c6259f4400a8"),
                            Description = "Süt, ekmek, yumurta",
                            DueDate = new DateTime(2025, 9, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDone = false,
                            Priority = 1,
                            Title = "Alışveriş yap"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Pazartesi toplantısı için slaytlar",
                            DueDate = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDone = false,
                            Priority = 2,
                            Title = "Sunum hazırla"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "30 dk koşu",
                            DueDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDone = true,
                            Priority = 0,
                            Title = "Spor"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Yağ değişimi ve filtreler",
                            DueDate = new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDone = false,
                            Priority = 1,
                            Title = "Araba bakımı"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
