// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using News.Repositories;

#nullable disable

namespace News.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    [Migration("20251012201339_StartPoint")]
    partial class StartPoint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("News.Models.NewsArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("NewsArticles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "BTK Akademi",
                            Content = "<p>Yapay zeka, medya kuruluşlarında içerik üretimini hızlandırmaya devam ediyor...</p>",
                            PublishedAt = new DateTime(2025, 1, 5, 9, 30, 0, 0, DateTimeKind.Utc),
                            Slug = "yapay-zeka-destekli-haber-uretimi",
                            Status = "Published",
                            Summary = "Yapay zeka destekli iş akışları dijital haber odalarını nasıl dönüştürüyor?",
                            Title = "Yapay Zeka Destekli Haber Üretimi"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Zafer Yazar",
                            Content = "<p>ASP.NET Core 9.0 güncellemesinde performans iyileştirmeleri ve API geliştirmeleri öne çıkıyor...</p>",
                            PublishedAt = new DateTime(2025, 2, 12, 14, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "aspnet-core-9-0-yenilikler",
                            Status = "Published",
                            Summary = "ASP.NET Core 9.0 sürümündeki en önemli yenilikler.",
                            Title = "ASP.NET Core 9.0’daki Yenilikler"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Genel Yayın Yönetmeni",
                            Content = "<p>Bu hafta öne çıkan konulara odaklanıyor ve üretim planımızın detaylarını paylaşıyoruz...</p>",
                            Slug = "editor-notlari",
                            Status = "Draft",
                            Summary = "Haftalık editoryal öne çıkanlar ve yaklaşan içerik planları.",
                            Title = "Editör Notları"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
